### ISSUE TITLE
bootstrap.sh 

### ISSUE THREAD

**Issue by rajeevkannav** [rootstrap/rails_hotwire_base#36]
Where is that `bootstrap.sh` mentioned in README ?

**Comment by juan-apa** [comment]
Thanks for bringing this to our attention. Some parts of the README got copied over from our [rails api base](https://github.com/rootstrap/rails_api_base/). You can check out the `bootstrap.sh` file [here](https://github.com/rootstrap/rails_api_base/blob/master/bootstrap.sh) while we sort this out!. If you feel brave, you can contribute to the project by doing the PR yourself.

**Comment by rajeevkannav** [comment]
Can you please check this [PR](https://github.com/rootstrap/rails_hotwire_base/pull/37)

**Comment by JuannFerrari** [comment]
PR #37 has been merged, thanks for the contribution, I will close the issue.
